##### Fig 4 (Luebeck et al, PLoS CompBio)
##### read Bhat fit outputs generated by lkh fortran program (iflag=3), e.g.
##### 

haz.table = read.table(file='hazOut.WF.1960BC.conv2s')
names(haz.table)  = c('age','year','cases','pyrs','exp.d','obs.d')
haz.table = as.data.frame(haz.table)
haz.table$byear = haz.table$year - haz.table$age

years = 1975:2016

cond = haz.table$age > 70 & haz.table$byear < max(haz.table$byear)
haz = haz.table[cond,]
year = haz$year = haz$byear+haz$age
tmp = split(data.frame(cases=haz$cases,pyrs=haz$pyrs),year)
haz.by.year = 1.e5*unlist(lapply(tmp,function(x){dum=apply(x,2,sum);dum[1]/dum[2]})) 

tmpE = split(haz$exp.d,haz$year)
E.mean = unlist(lapply(tmpE,mean))

plot(1975:2016,haz.by.year,ylab='incidence /100,000',
     xlab='year',ylim=c(0,25),pch=1,cex=.7,col=1,cex.lab=1.3)
lines(smooth.spline(years,haz.by.year,df=4),lwd=1,col=2)
lines(1975:2016,1.e5*E.mean,col=1,lwd=2,lty=1)


cond = haz.table$age > 60 & haz.table$age < 70 & haz.table$byear < max(haz.table$byear)
haz = haz.table[cond,]
year = haz$year = haz$byear+haz$age
tmp = split(data.frame(cases=haz$cases,pyrs=haz$pyrs),year)
haz.by.year = 1.e5*unlist(lapply(tmp,function(x){dum=apply(x,2,sum);dum[1]/dum[2]})) 

tmpE = split(haz$exp.d,haz$year)
E.mean = unlist(lapply(tmpE,mean))

points(1975:2016,haz.by.year,pch=2,cex=.7,col=1)
lines(smooth.spline(years,haz.by.year,df=4),lwd=1,col=2)
lines(1975:2016,1.e5*E.mean,col=1,lwd=2,lty=2)

cond = haz.table$age > 50 & haz.table$age < 60 & haz.table$byear < max(haz.table$byear)
haz = haz.table[cond,]
year = haz$year = haz$byear+haz$age
tmp = split(data.frame(cases=haz$cases,pyrs=haz$pyrs),year)
haz.by.year = 1.e5*unlist(lapply(tmp,function(x){dum=apply(x,2,sum);dum[1]/dum[2]})) 

tmpE = split(haz$exp.d,haz$year)
E.mean = unlist(lapply(tmpE,mean))

points(1975:2016,haz.by.year,pch=3,cex=.7,col=1)
lines(smooth.spline(years,haz.by.year,df=4),lwd=1,col=2)
lines(1975:2016,1.e5*E.mean,col=1,lwd=2,lty=3)

legend('topright',c('age 50-59','age 60-69',' age 70+'),lty=rev(c(1:3)),pch=rev(c(1:3)),bty='n',
       y.intersp = 1.2, cex=1.1)
legend('topleft','C) white females',cex=1.2,bty='n')



#### ignore code below
#### model predictions (red color)

# only average specific age group, e.g. 60-69
cond = haz.table$age > 50 & haz.table$age < 60
haz = haz.table[cond,]
haz$year = haz$byear+haz$age

# byear = 1930
# haz = hazOut[hazOut$byear==byear+0.5,]
# plot(haz$age,100000*haz$hazE,type='l',lwd=2)
# points(haz$age,100000*haz$hazO,pch=19,cex=.6)

tmpE = split(haz$exp.d,haz$year)
tmpO = split(haz$obs.d,haz$year)

E.mean = unlist(lapply(tmpE,median))
E.upp =  unlist(lapply(tmpE,max))
E.low =  unlist(lapply(tmpE,min))

O.mean = unlist(lapply(tmpO,mean))

lines(1975:2016,1.e5*E.mean,col=2,lwd=2,lty=3)

